### ISSUE TITLE
Firefox 110.0 release notes seems to be missing a "Community Contributions" section

### ISSUE THREAD

**Issue by gorisanson** [mozilla/release-notes#21]
Hello!

The release notes for the previous versions of Firefox included the "Community Contributions" sections which listed code contributions from community members (i.e. non-employees). Some examples are the following:
https://www.mozilla.org/en-US/firefox/109.0/releasenotes/#community
https://www.mozilla.org/en-US/firefox/106.0/releasenotes/#community

When I checked the [Firefox 110.0 release notes](https://www.mozilla.org/en-US/firefox/110.0/releasenotes/), I found no "Community Contributions" section. Actually, I was waiting to see Firefox 110.0 release notes since I was expecting my code contributions for the version 110.0 ([Bug 1742337](https://bugzilla.mozilla.org/show_bug.cgi?id=1742337), [Bug 1807402](https://bugzilla.mozilla.org/show_bug.cgi?id=1807402)) would be listed on a "Community Contributions" section in the notes.

Are there some reason the "Community Contributions" section is omitted in this 110.0 release notes? If it is by some human mistake or something, can we add the "Community Contributions" section to the release notes? Also I think there can be some code contributions from other community members that should have been included on the section.

I also reported the same issue in the bugzilla but no one responded yet:
https://bugzilla.mozilla.org/show_bug.cgi?id=1816826

Thank you!

**Comment by pascalchevrel** [comment]
Hi @gorisanson I answered you in https://bugzilla.mozilla.org/show_bug.cgi?id=1816826, let's close the GitHub issue and follow up on Bugzilla.

**Comment by gorisanson** [comment]
@pascalchevrel Thank you!

**Comment by alexgibson** [comment]
Closing as duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1816826
