### ISSUE TITLE
Thunderbird 68 missing

### ISSUE THREAD

**Issue by msirringhaus** [mozilla/release-notes#7]
The releasenotes of Thunderbird 68 seem to be missing at the moment.

**Comment by msirringhaus** [comment]
Thunderbird 68.1 has been released in the meantime as well.

**Comment by pmac** [comment]
Sorry I missed seeing this. Thunderbird notes are stored in [this repo within Thunderbird's Github org](https://github.com/thundernest/thunderbird-notes).
